name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: bash scripts/buildprod.sh